# Generated by Django 3.1.2 on 2020-10-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0002_favoritecar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
