# Generated by Django 3.1.2 on 2020-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_user', '0004_useremail_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecar',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
