# Generated by Django 3.1.2 on 2020-10-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecar',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favoritecar',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favoritecar',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
