# Generated by Django 3.1.2 on 2020-10-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_post', '0002_auto_20201007_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecar',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
