# Generated by Django 3.1.2 on 2020-10-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_post', '0003_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecar',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='favoritecar',
            name='total_votes',
        ),
    ]
