# Generated by Django 3.1.2 on 2020-10-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_post', '0005_auto_20201017_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
